### PR TITLE
Filter fix

### PR DESCRIPTION
**Pull request by triggerNZ**

### CODE REVIEW

**Comment by triggerNZ** [comment]
Confirmed this fix works on the cluster

**Comment by dkristian** [comment]
@triggerNZ I pushed a commit that addresses an earlier inconsistency between `FeatureSource` and `ContextFeatureSource`. It doesn't affect the mechanism of your fix, but eliminates the need to introduce the `featureValue` member. I'm happy with the PR if you're happy with my change 👍 

Aside, this could also be fixed by moving pre-join filters from concrete data sources to abstract, which is now possible with the generated multi-way join stuff. There's still one hurdle that needs to be crossed in order to do that though, which is how to incorporate the context. I have a couple of ideas, but I'm not certain they won't lead down a rabbit hole, so I think the fix in this PR is most appropriate at this stage.

**Comment by triggerNZ** [comment]
@dkristian, I'm happy with your fix. it's more consistent and elegant

**Comment by dkristian** [comment]
Apologies, I'm retracting my approval 👎 

If the abstract source used to bind to the concrete source comes from the feature set (where the filters are declared), this PR would result in the filter being redundantly applied twice. The problem as I understand it was that a new abstract source was being used in the binding. There are some examples in the USERGUIDE that are probably leading people astray.

**Pull request closed without merging**
