### PR TITLE
Add link to identify latest coppersmith version

### PR DESCRIPTION
**Pull request by toddmowen**

### CODE REVIEW

**Comment by triggerNZ** [comment]
:+1:

**Comment by dkristian** [comment]
I get a 404 for that link, even when I'm logged in:
```
{
  "errors" : [ {
    "status" : 404,
    "message" : "Unable to find artifact versions"
  } ]
}
```

**Comment by triggerNZ** [comment]
Link doesn't work for me either

**Comment by toddmowen** [comment]
@dkristian @triggerNZ Try again now?

**Comment by dkristian** [comment]
👍 It's a shame there's no way to include the content of that resource in the rendered markdown, but it's still a good improvement.

**Pull request merged**
